name: Sync images to Aliyun
on:
#  schedule:
#    - cron: '0 0 * * *'
  push:
    paths:
#      - 'example/variables.yaml'
      - 'images.txt'
jobs:
  quay-to-aliyun:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TO_USERNAME }}
      TO_PASSWORD: ${{ secrets.TO_PASSWORD }}
    steps:
    - name: Quay to Aliyun
      run: |
        cat << EOF >config.yaml
        registries:
          aliyuncs:
            registry: https://registry.aliyuncs.com
            username: ${{ secrets.TO_USERNAME }}
            password: ${{ secrets.TO_PASSWORD }}
          quay:
            registry: https://quay.io
            repositories:
              - metallb/controller:v0.13.10
              - metallb/speaker:v0.13.10
              - metallb/controller:v0.13.11
              - metallb/speaker:v0.13.11
        sync-policy:
          from: quay
          to: aliyuncs
          dry-run: false
          replace:
            - old: metallb/
              new: kubedog/metallb_
          filters:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
        EOF
        registry-manager sync -c config.yaml

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
