name: Sync images to Aliyun
on:
#  schedule:
#    - cron: '0 0 * * *'
  push:
    paths:
      - 'images.txt'
jobs:
  dockerhub-to-aliyun:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.TO_USERNAME }}
      TO_PASSWORD: ${{ secrets.TO_PASSWORD }}
    steps:
    - name: Dockerhub to Aliyun
      run: |
        cat << EOF >config.yaml
        from:
          registry: https://registry-1.docker.io
        to:
          registry: https://registry.aliyuncs.com
        names:
          - openresty/openresty:1.19.3.1-alpine
        replace:
          - old: openresty/
            new: kubedog/openresty_
        rules:
          - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
        EOF
        sync-images --config config.yaml
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
